import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import NavBar from "./commons/NavBar";
import Providers from "./Providers";

// 폰트 설정
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 메타데이터
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout 컴포넌트
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      className={`${geistSans.variable} ${geistMono.variable} overflow-x-hidden`} // ✅ 가로 스크롤 방지
      lang="ko"
    >
      <body className="flex min-h-screen flex-col overflow-x-hidden bg-gray-100">
        <div className="flex min-h-0 flex-1">
          {/* 왼쪽 NavBar */}
          <NavBar />
          {/* 오른쪽 본문 */}
          <main className="flex min-h-0 min-w-0 flex-1 overflow-auto">
            <Providers>{children}</Providers>
          </main>
        </div>
      </body>
    </html>
  );
}
